mysql:
  properties:
    url: 'jdbc:mysql://localhost:3306/db_example'
    username: guest
#    password: '{cipher}AQCYo7+iAo64vIWjmhwbTEQzDhKHy7NPpNjTJim30g20FKK964+/Xgxohrsz4XtrRmVG+wnSwbKSh1ALEonQ/a2zslsTIPCFsrwT9Hamo1sMJgvuNjOYGped8rbjvyNGmutR/cVU6D5Keye+fOGZKGLeG6OeL0JPj4YXjbThR8xd25AeFhG4YUaPuxQ2FAacXgjtmY0zB5DyvgN5wavGOnJrY6E1cwcy+8tuCBvBNZF/5CumDmJFY/Jffis2I/QunImw2WeJCY9OYCtLP+Ly47MpmwqIYcuQ6OUlswDF6rGVzAOEX4ScemIWo/56glMxfhn3QnSeYyLMyLdMDly9G06AiajbJtdATLPIHCc4X8DfXG7qJLrzHK11A39wZRBW2jw='
    password: '{cipher}ee465e4a21ca4c4fae15cfb7805125584c3b9dce01321219159acb03d094c08d'
