mysql:
  properties:
    url: 'jdbc:mysql://localhost:3306/db_example'
    username: devuser
#    password: '{cipher}AQCYo7+iAo64vIWjmhwbTEQzDhKHy7NPpNjTJim30g20FKK964+/Xgxohrsz4XtrRmVG+wnSwbKSh1ALEonQ/a2zslsTIPCFsrwT9Hamo1sMJgvuNjOYGped8rbjvyNGmutR/cVU6D5Keye+fOGZKGLeG6OeL0JPj4YXjbThR8xd25AeFhG4YUaPuxQ2FAacXgjtmY0zB5DyvgN5wavGOnJrY6E1cwcy+8tuCBvBNZF/5CumDmJFY/Jffis2I/QunImw2WeJCY9OYCtLP+Ly47MpmwqIYcuQ6OUlswDF6rGVzAOEX4ScemIWo/56glMxfhn3QnSeYyLMyLdMDly9G06AiajbJtdATLPIHCc4X8DfXG7qJLrzHK11A39wZRBW2jw='
    password: '{cipher}8b6597babdb05246904852f1a4feba7729cf8711c4f09a55c2dd30b565105979'
