server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/smartinrub/spring-centralized-configuration.git"
          refresh-rate: 5 # the config server will fetch updated configuration every 5 seconds
