server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavohirNarzullayev/config-cloud.git
          search-paths: config-properties
    bus:
      enabled: true
      id: config-server
